name: mess
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar:
  intl:
  flutter_riverpod: 
  flutter_hooks: 
  hooks_riverpod: 
  iconsax: 
  flutter_rating_bar: ^4.0.1
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  cloud_firestore: ^5.0.0
  internet_connection_checker: ^3.0.1
  carousel_slider: ^5.1.1
  flutter_datetime_picker_plus: ^2.0.1
  path_provider: ^2.1.1
  share_plus: ^7.0.1
  qr_flutter: ^4.0.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  
  uses-material-design: true
  assets:
    - assets/images/nashtapng.png
    - assets/images/tea.png
    - assets/images/google.png
