name: mess
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  persistent_bottom_nav_bar:
  intl:
  flutter_riverpod: 
  flutter_hooks: 
  hooks_riverpod: 
  iconsax: 
  lottie: 
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.12.0
  google_sign_in: ^6.1.5
  # firebase_analytics: ^10.10.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  
  uses-material-design: true
  assets:
    - assets/images/nashtapng.png
    - assets/images/tea.png
    - assets/images/google.png
